[nfs]
172.31.88.158 ansible_ssh_user='ec2-user'

[webservers]
172.31.94.117 ansible_ssh_user='ec2-user'
172.31.95.113 ansible_ssh_user='ec2-user'

[db]
172.31.91.3 ansible_ssh_user='ec2-user' 

[lb]
172.31.89.176 ansible_ssh_user='ubuntu'